-- MySQL Script generated by MySQL Workbench
-- Sat Feb 27 16:57:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Santos-FC
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Santos-FC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Santos-FC` DEFAULT CHARACTER SET utf8 ;
USE `Santos-FC` ;

-- -----------------------------------------------------
-- Table `Santos-FC`.`Ações_jogos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Santos-FC`.`Ações_jogos` (
  `Id_acoes` INT NOT NULL,
  `Nome_acoes` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_acoes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Santos-FC`.`Jogador_Santos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Santos-FC`.`Jogador_Santos` (
  `idJogador_Santos` INT NOT NULL AUTO_INCREMENT,
  `Nome_jogador` VARCHAR(45) NULL,
  PRIMARY KEY (`idJogador_Santos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Santos-FC`.`Jogador_Adversario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Santos-FC`.`Jogador_Adversario` (
  `Id_jogadorad` INT NOT NULL,
  `Nome_JogadorAD` VARCHAR(45) NULL,
  PRIMARY KEY (`Id_jogadorad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Santos-FC`.`Campeonato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Santos-FC`.`Campeonato` (
  `ID_Campeonato` INT NOT NULL,
  `Nome_Campeonato` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Campeonato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Santos-FC`.`Posições`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Santos-FC`.`Posições` (
  `Id_Posicao` INT NOT NULL AUTO_INCREMENT,
  `Posição` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Posicao`),
  UNIQUE INDEX `Id_Posicao_UNIQUE` (`Id_Posicao` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = Pos001;


-- -----------------------------------------------------
-- Table `Santos-FC`.`Estádios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Santos-FC`.`Estádios` (
  `ID_Estadio` INT NOT NULL,
  `Nome_Estadio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Estadio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Santos-FC`.`Times`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Santos-FC`.`Times` (
  `ID_Time` INT NOT NULL AUTO_INCREMENT,
  `Nome_Time` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Time`),
  UNIQUE INDEX `ID_Time_UNIQUE` (`ID_Time` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Santos-FC`.`Jogos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Santos-FC`.`Jogos` (
  `ID_Jogo` INT NOT NULL,
  `ID_Campeonato` INT NOT NULL,
  `Data` DATE NOT NULL,
  `ID_Mandante` INT NOT NULL,
  `Placar_Mandante` INT NOT NULL,
  `ID_Visitante` INT NOT NULL,
  `Placar_Visitante` INT NOT NULL,
  `ID_Estadio` INT NOT NULL,
  `Possebola_mand` INT NOT NULL,
  `Possebola_vis` INT NOT NULL,
  `Finalizacaonogol_mand` INT NOT NULL,
  `Finalizacaonogol_vis` INT NOT NULL,
  `Finalizacaofora_mand` INT NOT NULL,
  `Finalizacaofora_vis` INT NOT NULL,
  `Chutestravados_mand` INT NOT NULL,
  `Chutestravados_vis` INT NOT NULL,
  `Escanteio_mand` INT NOT NULL,
  `Escanteio_vis` INT NOT NULL,
  `Impedimento_mand` INT NOT NULL,
  `Faltas_mand` INT NOT NULL,
  `Faltas_vis` INT NOT NULL,
  `Cartaoamarelo_mand` INT NOT NULL,
  `Cartaoamarelo_vis` INT NOT NULL,
  `Cartaovermelho_mand` INT NOT NULL,
  `Cartaovermelho_vis` INT NOT NULL,
  `Grandesoportunidades_mand` INT NOT NULL,
  `Grandesoportunidades_vis` INT NOT NULL,
  `Chancesperdidas_mand` INT NOT NULL,
  `Chancesperdidas_vis` INT NOT NULL,
  `Chutestrave_mand` INT NOT NULL,
  `Chutetrave_vis` INT NOT NULL,
  `Finalizacaodarea_mand` INT NOT NULL,
  `Finalizacaodarea_vis` INT NOT NULL,
  `Finalizacaofarea_mand` INT NOT NULL,
  `Finalizacaofarea_vis` INT NOT NULL,
  `Defesasgoleiro_mand` INT NOT NULL,
  `Defesasgoleiro_ vis` INT NOT NULL,
  `Passes_mand` INT NOT NULL,
  `Passes_vis` INT NOT NULL,
  `Precpasses_mand` INT NOT NULL,
  `Precpasses_vis` INT NOT NULL,
  `Bolaslongas_mand` INT NOT NULL,
  `Bolaslongas_vis` INT NOT NULL,
  `Bolaslongascertas_mand` INT NOT NULL,
  `Bolaslongascertas_ad` INT NOT NULL,
  `Cruzamentos_mand` INT NOT NULL,
  `Cruzamentos_vis` INT NOT NULL,
  `Cruzamentoscertos_mand` INT NOT NULL,
  `Cruzamentoscertos_vis` INT NOT NULL,
  `Dribles_mand` INT NOT NULL,
  `Dribles_vis` INT NOT NULL,
  `Driblescertos_mand` INT NOT NULL,
  `Driblescertos_vis` INT NOT NULL,
  `Perdapossedebola_mand` INT NOT NULL,
  `Perdapossedebola_vis` INT NOT NULL,
  `Desarmes_mand` INT NOT NULL,
  `Desarmes_vis` INT NOT NULL,
  `Interceptacoes_mand` INT NOT NULL,
  `Interceptacoes_vis` INT NOT NULL,
  PRIMARY KEY (`ID_Jogo`),
  INDEX `ID_Campeonato_idx` (`ID_Campeonato` ASC) VISIBLE,
  INDEX `ID_Mandante_idx` (`ID_Mandante` ASC) VISIBLE,
  INDEX `ID_Visitante_idx` (`ID_Visitante` ASC) VISIBLE,
  INDEX `ID_Estadio_idx` (`ID_Estadio` ASC) VISIBLE,
  CONSTRAINT `ID_Campeonato`
    FOREIGN KEY (`ID_Campeonato`)
    REFERENCES `Santos-FC`.`Campeonato` (`ID_Campeonato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_Mandante`
    FOREIGN KEY (`ID_Mandante`)
    REFERENCES `Santos-FC`.`Times` (`ID_Time`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_Visitante`
    FOREIGN KEY (`ID_Visitante`)
    REFERENCES `Santos-FC`.`Times` (`ID_Time`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_Estadio`
    FOREIGN KEY (`ID_Estadio`)
    REFERENCES `Santos-FC`.`Estádios` (`ID_Estadio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Santos-FC`.`Relatório_Escalação`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Santos-FC`.`Relatório_Escalação` (
  `ID_Jogador` INT NOT NULL,
  `ID_Posicao` INT NOT NULL,
  `ID_Jogo` INT NOT NULL,
  INDEX `ID_Jogador_idx` (`ID_Jogador` ASC) VISIBLE,
  INDEX `ID_Posicao_idx` (`ID_Posicao` ASC) VISIBLE,
  INDEX `ID_Jogo_idx` (`ID_Jogo` ASC) VISIBLE,
  CONSTRAINT `ID_Jogador`
    FOREIGN KEY (`ID_Jogador`)
    REFERENCES `Santos-FC`.`Jogador_Santos` (`idJogador_Santos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_Posicao`
    FOREIGN KEY (`ID_Posicao`)
    REFERENCES `Santos-FC`.`Posições` (`Id_Posicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_Jogo`
    FOREIGN KEY (`ID_Jogo`)
    REFERENCES `Santos-FC`.`Jogos` (`ID_Jogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Santos-FC`.`Relatório_Ações`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Santos-FC`.`Relatório_Ações` (
  `ID_Jogo` INT NOT NULL,
  `ID_Jogador` INT NOT NULL,
  `ID_Ações` INT NOT NULL,
  `Minutagem` INT NOT NULL,
  INDEX `ID_Jogador_idx` (`ID_Jogador` ASC) VISIBLE,
  INDEX `ID_Acoes_idx` (`ID_Ações` ASC) VISIBLE,
  INDEX `ID_Jogo_idx` (`ID_Jogo` ASC) INVISIBLE,
  CONSTRAINT `ID_Jogador`
    FOREIGN KEY (`ID_Jogador`)
    REFERENCES `Santos-FC`.`Jogador_Santos` (`idJogador_Santos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_Acoes`
    FOREIGN KEY (`ID_Ações`)
    REFERENCES `Santos-FC`.`Ações_jogos` (`Id_acoes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_Jogo`
    FOREIGN KEY (`ID_Jogo`)
    REFERENCES `Santos-FC`.`Jogos` (`ID_Jogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
